# Generated by Django 5.1 on 2024-10-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_studentinfo_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentinfo',
            name='fathers_img',
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='mothers_img',
        ),
    ]
