# Generated by Django 5.1 on 2024-10-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_remove_studentinfo_fathers_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='class_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students_students', to='students.studentclassinfo'),
        ),
    ]
