# Generated by Django 5.1 on 2024-10-09 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0006_alter_attendance_id_alter_studentclassinfo_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MonthsofTheYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentsInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.studentclassinfo')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.monthsoftheyear')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.academicsession')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.paymentstatus')),
            ],
        ),
    ]
