# Generated by Django 5.1 on 2024-10-17 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('students', '0009_alter_studentinfo_class_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentsinformation',
            name='class_type',
        ),
        migrations.RemoveField(
            model_name='paymentsinformation',
            name='name',
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_students', to='students.studentclassinfo')),
            ],
        ),
    ]
