# Generated by Django 5.1 on 2024-10-17 13:07

import students.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_paymentsinformation_class_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsinformation',
            name='name',
            field=models.CharField(max_length=100, verbose_name=students.models.StudentInfo),
        ),
    ]
