# Generated by Django 5.1 on 2024-10-17 21:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_paymentsinformation_name'),
        ('students', '0010_alter_studentinfo_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsinformation',
            name='class_type',
            field=models.ForeignKey(default=1 , on_delete=django.db.models.deletion.CASCADE, to='students.studentclassinfo'),
        ),
        migrations.AlterField(
            model_name='paymentsinformation',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
