# Generated by Django 5.1 on 2024-10-17 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_alter_paymentsinformation_class_type'),
        ('students', '0011_alter_studentinfo_class_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsinformation',
            name='class_type',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='accounting_students', to='students.studentclassinfo'),
        ),
    ]
