# Generated by Django 5.1 on 2024-10-22 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_paymentstatus_alter_paymentsinformation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsinformation',
            name='status',
            field=models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=20),
        ),
        migrations.DeleteModel(
            name='PaymentStatus',
        ),
    ]
