# Generated by Django 5.1 on 2024-10-22 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0017_alter_paymentsinformation_status_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PaymentsInformation',
        ),
    ]
