# Generated by Django 5.1 on 2024-10-22 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0020_alter_paymentsinformation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentsinformation',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.paymentstatus'),
        ),
    ]
